coverage:
  status:
    project:
      default: false
      tests:
        target: 100%
        paths:
          - "tests/"
      app:
        target: auto
        threshold: 5%
        paths:
          - "src/"
    patch:
      default:
        target: auto
        threshold: 5%
        only_pulls: true
        paths:
          - "src/"
          - "tests/"

comment:
  layout: "condensed_header, condensed_files, condensed_footer"  # show component info in the PR comment
  require_changes: false

component_management:
  default_rules:
    statuses:
      - type: project
      - type: patch
  individual_components:
    - component_id: module_python
      name: python code
      paths:
        - src/python/**
    - component_id: module_ext
      name: C++ code
      paths:
        - src/ext_modules/**
    - component_id: module_tests
      name: tests
      paths:
        - tests/**
