coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        paths:
          - "src/"
          - "tests/"
      libsansmic:
        target: auto
        threshold: 5%
        paths:
          - "src/ext_modules/**/*.cpp"
          - "src/ext_modules/**/*.c"
      sansmic-py:
        target: auto
        threshold: 5%
        paths:
          - "src/python/**"
      tests:
        target: 100%
        paths:
          - "tests/**"
    patch:
      default:
        target: auto
        threshold: 5%
        only_pulls: true
        paths:
          - "src/"
          - "tests/"

comment:
  layout: "condensed_header, condensed_diff, condensed_files"  # show component info in the PR comment
  require_changes: false
  hide_project_coverage: false
  behavior: new

component_management:
  default_rules:
    statuses:
      - type: project
      - type: patch
  individual_components:
    - component_id: module_python
      name: python package
      paths:
        - src/python/**
    - component_id: module_ext
      name: external modules
      paths:
        - src/ext_modules/**/*.cpp
        - src/ext_modules/**/*.c
    - component_id: module_tests
      name: tests and examples
      target: 100%
      paths:
        - tests/**
