coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5
        base: auto
        paths:
          - "src/"
          - "tests/"
        # advanced settings
        branches:
          - main
          - dev
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths:
          - "tests/"  # only include coverage in "tests/" folder
        only_pulls: false

comment:
  layout: "header, diff, components"  # show component info in the PR comment

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: module_python
      name: pysansmic
      paths:
        - src/python/**
    - component_id: module_ext
      name: sansmic++
      paths:
        - src/ext_modules/**
    - component_id: module_tests
      name: tests
      paths:
        - tests/**
