coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5
        base: auto
        flags:
          - "unit"
        paths:
          - "src/"
          - "!tests/"
        # advanced settings
        # branches:
        #   - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
      tests:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths:
          - "tests/"  # only include coverage in "tests/" folder
        only_pulls: true
