name: Testing | Python 3.9--3.12 | all OSes

on:
  push:
    tags:
      - '*'
  pull_request:
    paths:
      - examples/**
      - src/**
      - tests/**
      - setup.py
    branches:
      - main
      - staging
  workflow_dispatch:

permissions:
  contents: read

jobs:
  full-suite:
    strategy:
      matrix:
        version: ["3.9", "3.10", "3.11", "3.12"]
        os: [windows-latest, macOS-13, macOS-latest, ubuntu-latest]
    uses: sandialabs/sansmic/.github/workflows/pytest-workflow.yml@951ebbd277e18b0a5b88a4e67535e262bc59f979
    with:
      version: ${{ matrix.version }}
      os: ${{ matrix.os }}
    secrets:
      coverage_token: ${{ secrets.CODECOV_TOKEN }}
